name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        
      - name: Setup Node.js
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci || npm install --legacy-peer-deps
        
      - name: Build
        run: npm run build
        env:
          VITE_PUBLIC_URL: "/cognis-workforce-tool"
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@65b5dfd4f5bcd3a7403bbc2959c144256167464e # v4.5.0
        with:
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
