name: Verify Fixes

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || echo "Linting failed but continuing"

      - name: Type check
        run: npx tsc --noEmit || echo "Type checking failed but continuing"

      - name: Build
        run: npm run build || echo "Build failed but continuing"

      - name: Report issues
        if: ${{ failure() }}
        run: echo "::warning::Verification failed. Please check the logs for details."
